logging:
  file:
    name: LogInfo.log
  level:
    com:
      awsiot: INFO
server:
  port: 9002
spring:
  application:
    name: SENSOR-DATA
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: $tanlyJoel99
    url: jdbc:mysql://localhost:3306/airquality
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
aws:
  accessKeyId: AKIARHZYVJ753AKQMJ24
  secretKeyId: BvNu8acRSlUGEFvDgM0uBW4C2QpYbubtUBoUA5gR
  snsEndpoint: arn:aws:sns:ap-south-1:085481312251:SafetySensor
